fix: lighthouse ci script문 수정

diff --git a/.github/workflows/work_flow_all.yaml b/.github/workflows/work_flow_all.yaml
--- a/.github/workflows/work_flow_all.yaml
+++ b/.github/workflows/work_flow_all.yaml
@@ -42,7 +42,11 @@ jobs:
         if: ${{ always() }}
       - name: Test
         run: npm test
-
         if: ${{ always() }}
-      - name: Format lighthouse score
-        uses: ./.github/actions/lighthouse
+
+      - name: Run Lighthouse CI
+        env:
+          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
+        run: |
+          npm install -g @lhci/cli
+          lhci autorun || echo "Fail to Run Lighthouse CI!"
